### PR TITLE
Hover effect added isuue #222

### PR DESCRIPTION
**Pull request by Lakshya2099**
I added a cool hover effect on the "Wildguard" on the top left of the navbar which looks appropriate to the websites theme

### CODE REVIEW

**Comment by Lakshya2099** [comment]
This is after hover effect


https://github.com/user-attachments/assets/4c174364-c255-4049-a908-28741541371c

**Comment by Lakshya2099** [comment]
Is there something not good as the code is not merged yet? feel free to tell me so that I can work on it

**Comment by Lakshya2099** [comment]
Is there any issue in the code as it has not been merged yet? please feel free to tell me so that I can work on it

**Comment by rahulkhandait-sde** [comment]
Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review. And also mention issue number.
Thank you!

**Pull request closed without merging**
