### PR TITLE
UI of Wildlife Conservation forum updated #1369

### PR DESCRIPTION
**Pull request by SaranshKhandelwal977**
I have updated the UI of Wildlife Conservation Forum
Before:
image

After:
image
Please merge this PR

### CODE REVIEW

**Comment by anuragverma108** [comment]
@SaranshKhandelwal977 The before & after part looks the same. What changes you made ?

**Comment by SaranshKhandelwal977** [comment]
Changed the top and bottom margins .
Changes the margins of "share your thoughts" text and "Submit" button
Changed the font style of "discover" now it looks like that there will be some discussions below it.

The updated UI is looking more good after changing the margins 


> @SaranshKhandelwal977 The before & after part looks the same. What changes you made ?

**Comment by anuragverma108** [comment]
Conflicting files
style.css

@SaranshKhandelwal977 
 Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by SaranshKhandelwal977** [comment]
@anuragverma108 ok I will do it

**Comment by SaranshKhandelwal977** [comment]
@anuragverma108 I have resolved the issues, please check.

**Comment by rahulkhandait-sde** [comment]
@SaranshKhandelwal977 Awesome contribution to Hacktoberfest'24! 🎉 Your work is super valuable. Keep up the great work!

**Pull request merged**
