### PR TITLE
Added hyperlinks to Donation buttons linking to the donation page #473

### PR DESCRIPTION
**Pull request by SACHINkgu**
Issue Description: We needed to link the "Donation" buttons in the donation section of our website to a dedicated donation page.

Solution:

Added a hyperlink ("<"a">" ) around each "Donation" button that redirects users to the donation.html page.
This ensures that when a user clicks on any "Donation" button, they are directed to the correct page for further action.
Summary: By wrapping each button with an anchor  tag, the donation buttons are now functional, providing seamless navigation to the donation page.

Wrapped Donation buttons with anchor tags to link to Donation.html page
image

### CODE REVIEW

**Comment by SACHINkgu** [comment]
Hello ! @anuragverma108  , 
I have added a hyperlink for the donation page.

- The Donation button has been incorporated in both the navigation bar and within the donation section, allowing users easy 
access to contribute. 
- Each button now links directly to donation.html, enhancing user experience and streamlining the donation process.

**Comment by SACHINkgu** [comment]
Reverts #473

**Comment by SACHINkgu** [comment]
Reverts #483

**Comment by SACHINkgu** [comment]
Hello i have resolved the conflict ,
 I have sent you my pull request please check it out , I hope you merge it , thank you.

**Comment by SACHINkgu** [comment]
@rahulkhandait-sde
Can you kindly merge this under #hacktoberfest-accepted label
Thankyou!

**Comment by rahulkhandait-sde** [comment]
Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
