### PR TITLE
FIXING ISSUE ##1456  make the login page more consistent

### PR DESCRIPTION
**Pull request by OKpoorav**
fix : #1456 

I made the login and the sign up page on a single page and made the transition in between them rather than having a new html file for each

### CODE REVIEW

**Comment by OKpoorav** [comment]
@anuragverma108 hi sir, pls review my PR

**Comment by PriyaGhosal** [comment]
@OKpoorav Attach SS

**Comment by OKpoorav** [comment]
Screenshot 2024-10-22 at 3 53 18 PM




Screenshot 2024-10-22 at 3 53 14 PM


here is the image of the new login and register page

**Comment by OKpoorav** [comment]
@PriyaGhosal Please check the ss attached

**Comment by rahulkhandait-sde** [comment]
Conflicting files
register.html

@OKpoorav Please resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
