### PR TITLE
Added dropdown functionality in nav bar

### PR DESCRIPTION
**Pull request by Kedar-sonavani**
Issue No:- #1206 
Before :- 
image

After :-

image

### CODE REVIEW

**Comment by Kedar-sonavani** [comment]
@rahulkhandait-sde  Please Merge this pr

**Comment by Kedar-sonavani** [comment]
why the label was removed

**Comment by PriyaGhosal** [comment]
@Kedar-sonavani After merging profile icon was enlarged which doesn't looked good. Do look into it and resolve the conflict . I have reverted this merge for now . Please open a new pr for review 
Thank you

**Comment by Kedar-sonavani** [comment]
I have make a new pr please just check once

**Pull request merged**
