### PR TITLE
fix: Improved the user inferface searchbar with appropriate styles.

### LINKED ISSUE #1167: Searchbar userinterface can be improved
hello @anuragverma108 ,
search bar User interface can be improved, therefore it is requested to assign me this issue under hacktoberfest 2024

### PR DESCRIPTION
**Pull request by SubramanyaKS**
Improved UI of search bar with below changes.
Before:
image

After:

image

closes #1167

### CODE REVIEW

**Comment by SubramanyaKS** [comment]
Hi @anuragverma108 ,
can you review PR.

**Comment by Parth04exe** [comment]
@SubramanyaKS 
why we can add the label hacktoberfest- accepted

**Comment by SubramanyaKS** [comment]
@Parth04exe ,
I think repo owner has been giving hacktoberfest-accepted upon merging pull request. When I saw the closed pull requests

**Comment by SubramanyaKS** [comment]
Hi @PriyaGhosal ,
I pulled latest change and created a new PR #1292 . Please review and merge it.
Thank you.

**Pull request closed without merging**
