### PR TITLE
Service-card scale up when we hover it.

### PR DESCRIPTION
**Pull request by AmanPatre**
This pull request adds a scaling effect to the service cards when hovered over, enhancing user interactivity and drawing more attention to the services. The effect uses a smooth transition with the transform: scale(1.04) CSS property, giving a subtle but noticeable enlargement when a user hovers over each card. This helps improve the visual appeal and makes the page feel more dynamic.

css scale up
card scale up

https://github.com/user-attachments/assets/58642a77-70e2-4e54-af52-fafa5dd6faa6

### CODE REVIEW

**Comment by AmanPatre** [comment]
Please assign this pull request to me

**Comment by AmanPatre** [comment]
please assign this pull request to me

**Comment by AmanPatre** [comment]
@anuragverma108  please look on to the merge request which I made

**Comment by rahulkhandait-sde** [comment]
Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
