### PR TITLE
Create ashu.py

### PR DESCRIPTION
**Pull request by ASHUTOSH-SHUKLAA**
Merging my first PR

### CODE REVIEW

**Comment by Aaradhya-07** [comment]
# Python Program to print Hello World
print("Hello World! I Don't Give a Bug")

**Comment by ASHUTOSH-SHUKLAA** [comment]
76r54d5r

**Comment by ASHUTOSH-SHUKLAA** [comment]
Python Prime Number Program

**Comment by rahulkhandait-sde** [comment]
Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
