### PR TITLE
Solve a major error with the login and signup popup and add navbar to the donation page 

### PR DESCRIPTION
**Pull request by MOHIT-IITP**
solved the #770  issue
Before: 
1: login button was not working (it was not opening the login and signup Popup)
2: user logo was not working 
3: there was no navbar in donation page (problem for user to come on home page )

After: 
1: Now the login button is Working 
2: User logo icon (click ) opens the login and signup popup
3: Add navbar to the Donation page for easy interaction

Screenshot 2024-10-09 at 9 59 26 PM
Screenshot 2024-10-09 at 10 00 02 PM
Screenshot 2024-10-09 at 10 00 08 PM

### CODE REVIEW

**Comment by MOHIT-IITP** [comment]
If you want to modify anything then tell me i will do it @anuragverma108

**Comment by MOHIT-IITP** [comment]
@anuragverma108  please check this

**Comment by PriyaGhosal** [comment]
@MOHIT-IITP 
Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by MOHIT-IITP** [comment]
@PriyaGhosal  please check #988

**Pull request closed without merging**
