### PR TITLE
enhanced the login page

### PR DESCRIPTION
**Pull request by Kedar-sonavani**
issue no :- #728
This pull request focuses on enhancing the user interface of the login page by adjusting the layout of the social media login buttons. The goal is to create a more user-friendly and visually appealing experience for users attempting to log in via social media accounts.

Key Changes:

Button Alignment:

Adjusted the alignment of the social media buttons to be centrally aligned, providing a more balanced look.
Added consistent spacing between buttons to prevent a cluttered appearance.
Button Styling:

Updated the button styles to match the overall theme of the login page, ensuring that they are visually cohesive with other UI elements.
Implemented hover effects for buttons to enhance interactivity and provide feedback to users.
Responsive Design:

Ensured that the layout is responsive, making it accessible on various devices, including mobile and tablet screens.
Utilized media queries to adjust button sizes and spacing on smaller screens for optimal usability.

### CODE REVIEW

**Comment by akash70629** [comment]
Attach screenshots of the changed sections After and before.  @Kedar-sonavani

**Comment by Kedar-sonavani** [comment]
image
image

**Comment by akash70629** [comment]
@Kedar-sonavani check this PR #863 , don't you think those social media buttons without text are more attractive than yours with text ? Just wander to know.

**Comment by Kedar-sonavani** [comment]
> @Kedar-sonavani check this PR #863 , don't you think those social media buttons without text are more attractive than yours with text ? Just wander to know.

Yeah but I think so my blur effect is better than that

**Comment by akash70629** [comment]
@Kedar-sonavani I appreciate your design bro !

**Pull request closed without merging**
