### PR TITLE
Contact Form Validation and Redirect Functionality Added Successfully 

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
I have made several enhancements to the contact form. 

1. Firstly, I implemented validation for the name field, which now requires a minimum of two characters and only accepts letters and spaces. If the input does not meet these criteria, an appropriate error message is displayed.

  2. Secondly, the email field now validates the format of the email address, ensuring that users enter a valid email; if not, an error message prompts them to correct it. 

 The message field requires a minimum length of ten characters, and if the input is too short or empty, an error message appears next to the field.

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
@anuragverma108 Check it added Successfully this Feature { Contact Form Validation and Redirect Functionality }
Thanks

**Comment by anuragverma108** [comment]
I am closing this PR. Unfortunately, due to a wrong PR that got merged, the website's structure became disorganized. We had to revert to the old code. Kindly pull the latest changes and create a new PR for your issue, as your current PR shows conflicts. I apologize for the inconvenience and appreciate your understanding. Looking forward to your new PR soon. Thank you! 😊

**Comment by syedmaazsaeed** [comment]
okay okay No Issue.

**Comment by syedmaazsaeed** [comment]
@anuragverma108 I push the code again don't worry. Assign me again an Issue { #246 }  I have posted it (pull request) Thanks.

**Pull request closed without merging**
